name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Build CSS
      run: npm run build-css
    - name: Deploy to happyprime.co
      if: success()
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --exclude=.git --exclude=.gitignore --exclude=.github --exclude=node_modules --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
    - name: Send deployment notification to Happy Prime Slack
      if: success()
      uses: rtCamp/action-slack-notify@v2.2.1
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: https://github.com/happyprime.png
        SLACK_CHANNE: river-deploys
        SLACK_USERNAME: Happy Prime
        SLACK_TITLE: Happy Prime theme deployment
        SLACK_MESSAGE: 'The theme for happyprime.co has been deployed :rocket:'
    - name: Send error notification to Happy Prime Slack
      if: failure()
      uses: rtCamp/action-slack-notify@v2.2.1
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_ICON: https://github.com/happyprime.png
        SLACK_COLOR: '#ff0000'
        SLACK_CHANNE: river-deploys
        SLACK_USERNAME: Happy Prime
        SLACK_TITLE: Happy Prime theme deployment
        SLACK_MESSAGE: 'Deployment was not successful. :red_circle:'
